#!/bin/bash
echo ""
echo "░░░░░░░░▄▄▄▀▀▀▄▄███▄░░░░░░░░░░░░░░░░░"
echo "░░░░░▄▀▀░░░░░░░▐░▀██▌░░░░░░░░░░░░░░░░"
echo "░░░▄▀░░░░▄▄███░▌▀▀░▀█░░░░░░░░░░░░░░░░"
echo "░░▄█░░▄▀▀▒▒▒▒▒▄▐░░░░█▌░░░░░░░░░░░░░░░"
echo "░▐█▀▄▀▄▄▄▄▀▀▀▀▌░░░░░▐█▄░░░░░░░░░░░░░░"
echo "░▌▄▄▀▀░░░░░░░░▌░░░░▄███████▄░░░░░░░░░"
echo "░░░░░░░░░░░░░▐░░░░▐███████████▄░░░░░░"
echo "░░░░░le░░░░░░░▐░░░░▐█████████████▄░░░"
echo "░░░░toucan░░░░░░▀▄░░░▐██████████████▄"
echo "░░░░░░has░░░░░░░░▀▄▄████████████████▄"
echo "░░░░░arrived░░░░░░░░░░░░█▀██████░░░░░"
echo ""

locatefiles() {
    botfile="/bot.py"
    botfile=$(pwd)$botfile
    logfile="/bot.log"
    logfile=$(pwd)$logfile
}

running() {
    if [[ $(ps aux|grep bot.py|grep -v grep|grep -v daemon|grep -v SCREEN) != "" ]]; then
        true
    else
        false
    fi
}

checkbackend() {
        if dpkg -l| grep ^ii|grep daemon|grep 'turns other' > /dev/null; then
            backend="daemon"
        elif dpkg -l| grep ^ii|grep screen|grep 'terminal multi' > /dev/null; then
            backend="screen"
        else
            backend="manual"
        fi
    return 0
}

setcommands() {
    status() {
        if running; then
            echo "PastaBot is running!"
        else
            echo "PastaBot is not running!"
        fi
    }
    clear() {
        : > $logfile
    }
    if [ "$backend" == "daemon" ]; then
        start() {
            daemon -r -n pasta-bot -O $logfile python $botfile
        }
        stop() {
            daemon -n pasta-bot --stop
        }
    elif [ "$backend" == "screen" ]; then
        start() {
            screen -d -m -S pasta-bot -t pasta-bot python $botfile > $logfile 2>&1
        }
        stop() {
            pid=`ps ax|grep -v grep|grep python|grep -v SCREEN|grep $botfile|awk '{print $1}'`
            kill $pid
        }
    elif [ "$backend" == "manual" ]; then
        start() {
            $botfile
        }
        stop() {
            pid=`ps ax|grep -v grep|grep python|grep $botfile|awk '{print $1}'`
            kill $pid
        }
    fi
}

processargs() {
    case $1 in
        start|-start|--start)
            if running; then
                echo "Cannot start! Bot is already running!"
                exit 1
            else
                echo "Starting PastaBot... ($backend)"
                start
            fi
        ;;
        stop|-stop|--stop)
            if running; then
                echo "Stopping PastaBot... ($backend)"
                stop
            else
                echo "Cannot stop! Bot is not already running!"
                exit 1
            fi
        ;;
        restart|-restart|--restart)
            if running; then
                echo "Restarting PastaBot... ($backend)"
                stop
                sleep 3
                start
            else
                echo "Cannot restart! Bot is not already running!"
                exit 1
            fi
        ;;
        clear|-clear|--clear)
            echo "Clearing logs..."
            clear
        ;;
        status|-status|--status)
            status
        ;;
        *)
            usage="usage: ./pasta-bot {start|stop|restart|clear|status}"
            echo $usage
        ;;
    esac
}

main() {
    locatefiles
    checkbackend
    setcommands
    processargs $1
}

main $*
exit 0
